2020-12-29 22:17:05 logger_cla.py[line:33] INFO a
2020-12-29 22:17:05 logger_cla.py[line:34] DEBUG a
2020-12-29 22:17:05 logger_cla.py[line:35] ERROR a
2020-12-29 22:17:05 logger_cla.py[line:39] ERROR message.
Traceback (most recent call last):
  File "/home/caisi/PycharmProjects/BookStore/utils/logger_cla.py", line 37, in <module>
    raise TypeError('Test')
TypeError: Test
2020-12-29 22:18:06 logger_cla.py[line:33] INFO a
2020-12-29 22:18:06 logger_cla.py[line:34] DEBUG a
2020-12-29 22:18:06 logger_cla.py[line:35] ERROR a
2020-12-29 22:18:06 logger_cla.py[line:39] ERROR message.
Traceback (most recent call last):
  File "/home/caisi/PycharmProjects/BookStore/utils/logger_cla.py", line 37, in <module>
    raise TypeError('Test')
TypeError: Test
